---
title: "R Notebook"
output: html_notebook
---


# call libraries
```{r}
library(tidyverse)
library(janitor)
```


# call data
```{r}
flights_joined <- read_csv(here::here("clean_data/flights_joined.csv")) %>% 
  clean_names()
```


# dep_delay - outliers exploratory
```{r}
# -----------------------------------
# Histogram
# -----------------------------------
flights_joined %>% 
  ggplot() +
  aes(x = dep_delay) +
  geom_histogram(bins = 30, color = "white", fill = "firebrick") +
  labs(title = "Distribution of departure delay") +
  theme_minimal() +
  theme(strip.background = element_rect(fill = "grey80", colour = "white"),
        strip.text     = element_text(face = "bold"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())


# -----------------------------------
# Boxplot
# -----------------------------------
flights_joined %>% 
  ggplot() +
  aes(x = dep_delay, y = 1) + 
  geom_boxplot(outlier.colour = NA) +
  geom_point(position = position_jitter(height = .2), color = 4, alpha = .3) +
  labs(title = "Distribution of departure delay",
       subtitle = "minutes",
       x = NULL,
       y = NULL) +
  scale_x_continuous(breaks = seq(-120, 1548, 120), limits = c(-120, 1600)) + 
  theme_minimal() +
  theme(strip.background = element_rect(fill = "grey80", colour = "white"),
        strip.text       = element_text(face = "bold"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())

```


# weather condictions vector
```{r}
weather_variables <- c("temp", "dewp", "humid", "precip", "visib", 
                       "wind_speed", "wind_dir", "wind_gust", "pressure")
```

## scatterplot dep_delay VS weather - drop na
```{r}
# --------------------------------------------------
# function
# ------------------------------------------------
scatter_weather_drop_na <- function(dataset, airport_origin, weather_var){
  dataset %>% 
    filter(origin == airport_origin) %>% 
    pivot_longer(cols = c(temp:visib),
                 names_to = "weather_condition",
                 values_to = "value") %>% 
    select(dep_delay, weather_condition, value) %>% 
    filter(weather_condition == weather_var) %>%
    ggplot(aes(x = value, y = dep_delay)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +
    labs(title = str_c("Relationship: dep_delay VS ", weather_var, sep = ""),
         y = "dep_delay",
         x = weather_var) +
    theme_minimal() +
    theme(panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank())
}


for (condition in weather_variables){
  print(
    scatter_weather_drop_na(
      dataset = flights_joined, 
                airport_origin = "EWR", 
                 weather_var = condition)
    )
}
```