---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(janitor)
```


```{r}
flights_joined <- read_csv(here::here("clean_data/flights_joined.csv"))

flights_joined <- flights_joined %>% 
  clean_names() %>% 
  remove_empty(c("rows", "cols"))
```

# weather longer
```{r}
flights_joined_weather_longer <- flights_joined %>% 
  pivot_longer(cols      = c(43:50),
               names_to  = "weather_condition",
               values_to = "value")
```

# bloxplot 
```{r}
func_weather_longer <- function(dataset, 
                                weather_1, weather_2, weather_3, weather_4){
  
  dataset %>% 
    filter(weather_condition %in% c(weather_1, weather_2, weather_3, weather_4)) %>% 
    ggplot() +
    aes(x = value, y = 1) + 
    geom_boxplot(outlier.colour = NA) +
    geom_point(position = position_jitter(height = .2), color = 4, alpha = .3) +
    facet_wrap(~ weather_condition, nrow = 4, scales = "free") +
    labs(title = "Outlier Analysis",
         subtitle = "",
         x = NULL,
         y = NULL) +
    theme_minimal() +
    theme(strip.background = element_rect(fill = "grey80", colour = "white"),
          strip.text       = element_text(face = "bold"),
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank())
}
```

```{r}
func_weather_longer(dataset   = flights_joined_weather_longer, 
                    weather_1 = "temp", 
                    weather_2 = "depw", 
                    weather_3 = "humid", 
                    weather_4 = "wind_dir")
```
```{r}
func_weather_longer(dataset   = flights_joined_weather_longer, 
                    weather_1 = "wind_speed", 
                    weather_2 = "wind_gust", 
                    weather_3 = "precip", 
                    weather_4 = "pressure")
```
# Outliers
```{r}
# A futher understanding of bloxplot teel us in number.
bloxpot_summary <- flights_joined_weather_longer %>% 
  group_by(weather_condition) %>% 
  summarise(
    #Q1: the value splitting the distribution into a lower 25% and higher 75%.
    #Q2: the value splitting the distribution into a lower 50% and higher 50%.
    #Q3: the value splitting the distribution into a lower 75% and higher 25%.
    #IRQ: Interquartile range is the range in which 50% of the values fall
    Q1        = quantile(value, 0.25, na.rm = TRUE),
    Q2_median = quantile(value, 0.5,  na.rm = TRUE),
    Q3        = quantile(value, 0.75, na.rm = TRUE),
    IRQ       = Q3 - Q1,  #or IRQ = IRQ(bill_length_mm)
    
    lower_whisker = Q1 - 1.5 * IRQ,
    upper_whisker = Q3 + 1.5 * IRQ,

    
    # how many values are beyond upper and lower whisker - potential outliers
    nr_outlier_upper  = sum(value > upper_whisker, na.rm = TRUE),
    nr_outlier_lower  = sum(value < lower_whisker, na.rm = TRUE)
    )

bloxpot_summary
```

# weather distribution
```{r}
flights_joined_weather_longer %>% 
  group_by(weather_condition) %>% 
  ggplot() +
  aes(x = value) +
  geom_histogram(bins = 30, color = "white", fill = "firebrick") +
  facet_wrap(~weather_condition, scales = "free", ncol = 3) +
  theme_minimal() +
  theme(strip.background = element_rect(fill = "grey80", colour = "white"),
        strip.text     = element_text(face = "bold"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())
```
# NA
```{r}
flights_joined %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
```
```{r}
  flights %>% 
  select(dep_delay, dest, air_time, distance, name, temp, dewp,humid, 
         wind_dir, wind_speed, wind_gust, precip, pressure, visib) %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
```



```{r}
flights %>% 
  distinct(manufacturer)
```


