---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(tsibble)
library(lubridate)
```


```{r}
flights_joined <- read_csv(here::here("clean_data/flights_joined.csv")) %>% 
  clean_names()
```

```{r}
flights <- flights_joined 
# %>% 
#   select(!ends_with("_weather"), -year_planes, -key_origin_time)


flights_newark <- flights %>% 
  filter(tzone == "America/New_York") %>% 
  filter(name_airports == "Newark Liberty International Airport")


flights_ny <- flights %>% 
  filter(tzone == "America/New_York" & !name_airports == "Newark Liberty International Airport")
```



# Comparison NY airports
## Total flights 
```{r}
# ----------------------------------------------------------------------------
# Total flights per NY airport
# ----------------------------------------------------------------------------
total_flights_ny_airports <- flights %>% 
  drop_na(flight) %>% 
  filter(tzone == "America/New_York") %>%
  group_by(name_airports) %>% 
  summarise(total_flights = n())
  

# ----------------------------------------------------------------------------
# Total departure delay per NY airport
# ----------------------------------------------------------------------------
total_flights_delay_ny_airports <- flights %>% 
  drop_na(flight) %>% 
  filter(tzone == "America/New_York") %>%
  filter(dep_delay > 0) %>% 
  group_by(name_airports) %>% 
  summarise(delay_flights = n())


# ----------------------------------------------------------------------------
# join all
# ----------------------------------------------------------------------------
flights_ny_airports <- full_join(x = total_flights_ny_airports, 
                                 y = total_flights_delay_ny_airports)  %>% 
  mutate(perc_delay = round(delay_flights / total_flights *100, digits = 1),
         total_perc_delay = str_c(delay_flights, " (", perc_delay, " % )", sep = ""))
flights_ny_airports

# ----------------------------------------------------------------------------
# plot
# ----------------------------------------------------------------------------  
flights_ny_airports %>% 
  pivot_longer(cols = ends_with("_flights"),
               names_to = "flights",
               values_to = "number_flights") %>% 
  ggplot(aes(x = number_flights, y = name_airports, fill = flights)) +
  geom_col(position = "dodge") +
  labs(title = "Number of flights in New York airports",
       subtitle = "Total number and delayed departure flights",
       y = NULL,
       x = NULL) +
  geom_text(aes(label = number_flights),
            position = position_dodge(0.9),
            vjust = 0.5, hjust = -0.1) +
  theme_minimal() +
  xlim(0, 130000) +
  theme(
    panel.grid.major.y = element_blank(),
    legend.position = "bottom",
    legend.title = element_blank(),
    plot.title          = element_text(vjust = 3),
    plot.subtitle       = element_text(color = "grey30", vjust = 3)) +
  scale_fill_manual(values = c("firebrick", "grey70")
  )

```
## Percentage dep_delay variation per month
```{r}
library(lubridate)

# ----------------------------------------------------------------------------
# Total number of flights each NY airport had per month across all year 2017
# ----------------------------------------------------------------------------
flights_month_ny_airport <- 
  flights %>% 
  drop_na(flight) %>% 
  filter(tzone == "America/New_York") %>%
  mutate(month = yearmonth(time_hour, label = TRUE, abbr = TRUE)) %>%
  group_by(month, name_airport) %>% 
  summarise(nr_flights = n())


# ----------------------------------------------------------------------------
# Total number of flights that departure delayed in each NY airport had per 
# month across all year 2017
# ----------------------------------------------------------------------------
flights_dep_delay_month_ny_airport <- flights %>% 
  mutate(month = yearmonth(time_hour, label = TRUE, abbr = TRUE)) %>%
  drop_na(flight, dep_delay) %>% 
  filter(tzone == "America/New_York") %>%
  filter(dep_delay > 0) %>% 
  group_by(month, name_airport) %>% 
  summarise(nr_flights_dep_delay = n())

# ----------------------------------------------------------------------------
# Join
# ----------------------------------------------------------------------------
dep_delay_info <- 
  full_join(x = flights_month_ny_airport,
            y = flights_dep_delay_month_ny_airport) %>% 
  mutate(perc_dep_delay = round(x = nr_flights_dep_delay / nr_flights * 100, 
                                digits = 1))


# ----------------------------------------------------------------------------
# Plot - Percentage flights departure delay per month
# ----------------------------------------------------------------------------
dep_delay_info %>% 
  mutate(name_airport = factor(name_airport, levels = 
                                  c("Newark Liberty International Airport",
                                    "La Guardia Airport",
                                    "John F Kennedy International Airport"))) %>%
  ggplot(aes(x = month, y = perc_dep_delay, color = name_airport)) +
  geom_line(position = "dodge", aes(linetype = name_airport, size = name_airport)) +
  geom_point() +
  labs(title = "Percentage of delayed departure flights per month",
       subtitle = "New York Airports",
       y = NULL,
       x = NULL) +
  scale_y_continuous(labels = paste(c(seq(0,100, 10)), "%"),
                     breaks = seq(0, 100, 10),
                     limits = c(20, 50)) +
  scale_x_yearmonth(date_labels = "%Y \n %b", 
                    date_breaks = "1 month") +
  scale_color_manual(values = c("firebrick", "#D29F00", "steelblue")) +
  scale_size_manual(values = c(1.9, 0.8, 0.8)) +
  scale_linetype_manual(values = c("solid", "dashed", "dashed")) +
  theme_minimal() +
    theme(
        panel.grid.major.y  = element_line(size = 0.5, color = "grey70"),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        plot.title          = element_text(vjust = 3),
        plot.subtitle       = element_text(color = "grey30", vjust = 3),
        plot.caption        = element_text(size = 10, hjust = 0.5),
        legend.position = "bottom",
        legend.title = element_blank()
       )

```


# Statistical TESTS

# NEWARK AIRPORT


## Number fligths per month
```{r}
newark_nr_flights <- flights_newark %>%
  mutate(month = yearmonth(time_hour, label = TRUE, abrr = TRUE)) %>% 
  drop_na(month, flight, dep_delay) %>%
  group_by(month)


inner_join(x = newark_nr_flights %>% 
             filter(dep_delay > 0) %>% 
             summarise(nr_flights_yes_delay = n()),
           y = newark_nr_flights %>% 
             filter(dep_delay <= 0) %>% 
             summarise(nr_flights_no_delay = n())) %>%
  pivot_longer(cols = starts_with("nr_"),
               names_to = "type_flight",
               values_to = "value") %>% 
  ggplot() +
  aes(x = month, y = value, group = type_flight) +
  geom_col(aes(fill = type_flight), position = "dodge") +
  geom_text(
    aes(label = value), 
    position = position_dodge(0.9),
    angle = 90
  ) +
  labs(title = "Newark Airport: number of flights per month",
       subtitle = "Departed on time VS Departed delayed",
       x = NULL,
       y = NULL) +
  scale_x_yearmonth(date_labels = "%b", 
                    date_breaks = "1 month") +
  scale_fill_manual(values = c("steelblue", "grey70")) +
  theme_minimal()+
  theme(
    panel.grid.minor.x = element_blank(),
    panel.grid.major.x = element_blank(),
    plot.title = element_text(vjust = 3),
    plot.subtitle = element_text(color = "grey30", vjust = 3),
    legend.position = "bottom",
    legend.title = element_blank()
  )
    
    ```

## Number of flighs per Airline
```{r}
flights_per_airline <- flights_newark%>% 
  filter(origin == "EWR") %>% 
  group_by(name) %>% 
  summarise(nr_flights = n()) %>% 
  arrange(desc(nr_flights))

flights_per_airline %>% 
  ggplot() +
  aes(x = nr_flights, y = reorder(name, nr_flights), fill =  nr_flights == max(nr_flights)) +
  geom_col() + 
  geom_text(aes(label = nr_flights), 
            # position = position_stack(vjust = 0.5), 
            size = 4, 
            hjust = -0.1) +
  labs(title = "Total number of flights per Airline",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(
    panel.grid.major.y = element_blank(),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("grey60","steelblue")) +
  xlim(0, 60000)




```

## Airline with more delayed departure per month
```{r}
flights_newark %>% 
  mutate(month = yearmonth(time_hour, label = TRUE, abrr = TRUE)) %>% 
  filter(origin == "EWR") %>% 
  filter(dep_delay > 0) %>% 
  group_by(name, month) %>% 
  summarise(nr_flights_delay = n()) %>%
  ungroup() %>%
  group_by(month) %>%
  slice_max(nr_flights_delay,
            n = 1, 
            with_ties = TRUE) %>% 
    ggplot() +
  aes(x = month, y = nr_flights_delay, fill = name) %>% 
  geom_col(position = "dodge") +
  labs(
    title = "Airline with more delayed departure per month",
    subtitle = "Total delayed departure of those airline",
    x = NULL,
    y = NULL
  ) +
  scale_x_yearmonth(date_labels = "%b", 
                    date_breaks = "1 month") +
  scale_fill_manual(values = c("#D29F00", "#D29F00")) +
  theme_minimal()+
  theme(
    panel.grid.minor.x = element_blank(),
    panel.grid.major.x = element_blank(),
    plot.title = element_text(vjust = 3),
    plot.subtitle = element_text(color = "grey30", vjust = 3),
    legend.position = "bottom",
    legend.title = element_blank()
  )
```










## Airline with more delayed departure per month
```{r}
flights_newark %>% 
  mutate(month = yearmonth(time_hour, label = TRUE, abrr = TRUE)) %>% 
  filter(origin == "EWR") %>% 
  filter(dep_delay > 0) %>% 
  group_by(name, month) %>% 
  summarise(nr_flights_delay = n()) %>%
  ungroup() %>%
  group_by(month) %>%
  slice_max(nr_flights_delay,
            n = 1, 
            with_ties = TRUE) %>% 
    ggplot() +
  aes(x = month, y = nr_flights_delay, fill = name) %>% 
  geom_col(position = "dodge") +
  labs(
    title = "Airline with more delayed departure per month",
    subtitle = "Total delayed departure of those airline",
    x = NULL,
    y = NULL
  ) +
  scale_x_yearmonth(date_labels = "%b", 
                    date_breaks = "1 month") +
  scale_fill_manual(values = c("#D29F00", "#D29F00")) +
  theme_minimal()+
  theme(
    panel.grid.minor.x = element_blank(),
    panel.grid.major.x = element_blank(),
    plot.title = element_text(vjust = 3),
    plot.subtitle = element_text(color = "grey30", vjust = 3),
    legend.position = "bottom",
    legend.title = element_blank()
  )





# 
# 
# yes_delay_airline <- flights_newark %>% 
#   mutate(month = yearmonth(time_hour, label = TRUE, abrr = TRUE)) %>% 
#   filter(origin == "EWR") %>% 
#   filter(dep_delay > 0) %>% 
#   group_by(name, month) %>% 
#   summarise(nr_flights_delay = n()) %>%
#   ungroup() %>%
#   group_by(month) %>%
#   slice_max(nr_flights_delay,
#             n = 1, 
#             with_ties = TRUE) %>%  
#   mutate(key = str_c(name, month, sep = ""))
# 
# 
# no_delay_airline <- flights_newark %>% 
#     mutate(month = yearmonth(time_hour, label = TRUE, abrr = TRUE)) %>% 
#   filter(origin == "EWR") %>% 
#   # filter(dep_delay > 0) %>% 
#   group_by(name, month) %>% 
#   summarise(nr_flights_total = n()) %>%
#   ungroup() %>%
#   group_by(month) %>%
#   slice_max(nr_flights_total,
#             n = 1, 
#             with_ties = TRUE) %>% 
#   mutate(key = str_c(name, month, sep = ""))
# 
# 
# 
# inner_join(yes_delay_airline,
#            no_delay_airline) %>% 
#   mutate(perc = round(nr_flights_delay / nr_flights_total *100, digits = 2)) %>% 
#   pivot_longer(cols = starts_with("nr_"),
#                names_to = "nr_flights",
#                values_to = "values") %>% 
#   ggplot() +
#   aes(x = month, y = values, fill = name) %>% 
#   geom_col(position = "dodge") +
#   labs(
#     title = "Airline with more delayed departure per month",
#     subtitle = "Total flights of those airline VS delayed departure",
#     x = NULL,
#     y = NULL
#   ) +
#   scale_x_yearmonth(date_labels = "%b", 
#                     date_breaks = "1 month") +
#   scale_fill_manual(values = c("steelblue", "grey70")) +
#   theme_minimal()+
#   theme(
#     panel.grid.minor.x = element_blank(),
#     panel.grid.major.x = element_blank(),
#     plot.title = element_text(vjust = 3),
#     plot.subtitle = element_text(color = "grey30", vjust = 3),
#     legend.position = "bottom",
#     legend.title = element_blank()
#   )
#   
  



```


```{r}

```











## weather condition
```{r}
# Mean of weather condition by delayed departure flights and on time departure flights
# -----------------------------------------------------------------------------
config <- flights_newark %>%
  mutate(month = yearmonth(time_hour, label = TRUE, abbr = TRUE)) %>% 
  rename(temperature = temp,
         precipitation = precip,
         visibility = visib,
         "wind direction" = wind_dir,
         "wind speed" = wind_speed,
         "wind gust" = wind_gust,
         ) %>% 
  pivot_longer(cols = c(36:44),
               names_to = "weather_condition",
               values_to = "value") %>% 
  drop_na(value) %>% 
  select(weather_condition, value, month, dep_delay) %>% 
  group_by(weather_condition, month)

on_time <- config %>% 
  filter(dep_delay <= 0) %>% 
  summarise(mean_on_time = mean(value))

delay <- config %>% 
  filter(dep_delay > 0) %>% 
  summarise(mean_delay = mean(value))


inner_join(on_time, delay) %>% 
  pivot_longer(cols = starts_with("mean") , 
               names_to = "record",
               values_to = "value") %>% 
  ggplot() +
  aes(x = month, y = value, color = record) +
  geom_line(position = "dodge", size = 1) + 
  scale_x_continuous(breaks = seq(1, 12, 1)) +
  scale_x_yearmonth(date_labels = "%b", 
                    date_breaks = "2 month") +
  facet_wrap(~ weather_condition, scales = "free", ncol = 3) +
  scale_color_manual(values = c(
    "mean_on_time" = "seagreen",
    "mean_delay" = "firebrick")
  ) +
  labs(title = "Weather conditions (mean values) by flights departured delay and on time",
       subtitle = "Newark Airport",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(strip.background = element_rect(fill = "grey80", colour = "white"),
        strip.text       = element_text(face = "bold"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        plot.subtitle = element_text(color = "grey30", vjust = 3))
```


## Departure delay per travel
```{r}
# -----------------------------------------------------------------------------
# Which travel happen most (on time or with delay)?
#   - Number of fights per travel (origin to dest)
# -----------------------------------------------------------------------------
total_travel <- flights %>% 
  mutate(origin_dest = str_c(origin, dest, sep = " - ")) %>% 
  select(dep_delay, flight, air_time, distance, name_airports, origin_dest) %>% 
  drop_na(flight) %>% 
  filter(name_airports == "Newark Liberty International Airport") %>% 
  group_by(origin_dest) %>% 
  summarise(total_flight = n())
  

# -----------------------------------------------------------------------------
# Which travel with departure delay happen most?
#   - Number of fights per travel (origin to dest)
#   - Total minutes of departure delay per travel
# -----------------------------------------------------------------------------
travel_delay <- flights %>% 
  mutate(origin_dest = str_c(origin, dest, sep = " - ")) %>% 
  select(dep_delay, flight, air_time, distance, name_airports, origin_dest) %>% 
  drop_na(flight, dep_delay, distance, air_time) %>% 
  filter(name_airports == "Newark Liberty International Airport") %>% 
  filter(dep_delay > 0) %>% 
  group_by(origin_dest, name) %>% 
  summarise(nr_flight_delay = n(),
            # sum_dep_delay = sum(dep_delay),
            distance = mean(distance),
            mean_air_time = round(mean(air_time), digits = 0))

# -----------------------------------------------------------------------------
# join all
#   Here it is possible to see, by trip from origin to destination, which trip
#   ends up having the most delays in #  percentage terms.
# -----------------------------------------------------------------------------
travel_summary <- full_join(total_travel, travel_delay, by = "origin_dest") %>% 
  mutate(perc_dep_delay = round(nr_flight_delay / total_flight, digits = 3), 
         .after = nr_flight_delay) %>% 
  arrange(desc(total_flight))

travel_summary 
```






















```{r}
dep_delay_newark <- flights_newark %>% 
  select(month, dep_delay) %>% 
  filter(dep_delay > 0) %>% 
  group_by(month) %>% 
  summarise(sum_dep_delay = sum(dep_delay)) 


dep_delay_ny <- flights_ny %>%
  drop_na(flight, dep_delay) %>% 
  filter(dep_delay > 0) %>% 
  select(month, dep_delay, name_airports) %>% 
  group_by(month, name_airports) %>% 
  summarise(sum_dep_delay = sum(dep_delay)) %>% 
  pivot_wider()

dep_delay_ny

dep_delay_neward_and_ny <- full_join(x = dep_delay_newark, 
                                     y = dep_delay_ny,
                                     suffix = c("_newark","_ny"), 
                                     by = "month")
dep_delay_neward_and_ny

dep_delay_neward_and_ny %>% 
  pivot_longer(cols = starts_with("sum"),
               names_to = "dep_delay",
               values_to = "total_delay") %>% 
  ggplot() +
  aes(x = month, y = total_delay, color = dep_delay) +
  geom_line(position = "dodge") +
  scale_x_continuous(breaks = seq(1, 12, 1)) +
  theme()
```   
