---
title: "R Notebook"
output: html_notebook
---


# call libraries
```{r}
library(tidyverse)
library(janitor)
library(tsibble)
library(ggplot2)
```

# call data
```{r}
flights_joined <- read_csv(here::here("clean_data/flights_joined.csv")) %>% 
  clean_names %>% 
  mutate(month = yearmonth(time_hour), .after = time_hour)
```



# NEW YORK AIRPORTS
## Total flights per airport
```{r}
# ----------------------------------------------------------------------------
# Total flights per NY airport
# ----------------------------------------------------------------------------
flights_ny_airports <- flights_joined %>% 
  group_by(name_airport) %>% 
  summarise(total_flights = n())
  

# ----------------------------------------------------------------------------
# Total departure delay per NY airport
# ----------------------------------------------------------------------------
flights_delay_ny_airports <- flights_joined %>% 
  filter(dep_delay > 0) %>% 
  group_by(name_airport) %>% 
  summarise(delay_flights = n())


# ----------------------------------------------------------------------------
# join all
# ----------------------------------------------------------------------------
# flights_ny_airports <- full_join(x = flights_ny_airports, 
#                                  y = flights_delay_ny_airports)  %>% 
#   mutate(perc_delay = round(delay_flights / total_flights *100, digits = 1),
#          total_perc_delay = str_c(delay_flights, " (", perc_delay, " % )", sep = ""))
# flights_ny_airports


flights_ny_airports <- full_join(x = flights_ny_airports, 
                                 y = flights_delay_ny_airports)  %>% 
  mutate(percentage_delays = round(delay_flights / total_flights *100, digits = 1))
         # total_perc_delay = str_c(delay_flights, " (", perc_delay, " % )", sep = ""))

flights_ny_airports





# ----------------------------------------------------------------------------
# plot   steelblue   #E69F00"
# ----------------------------------------------------------------------------  
flights_ny_airports %>% 
  pivot_longer(cols = ends_with("_flights"),
               names_to = "flights",
               values_to = "number_flights") %>% 
  ggplot(aes(x = number_flights, y = name_airport, fill = flights)) +
  geom_col(position = "dodge") +
  labs(title = "Flights in New York airports",
       subtitle = "Total number and delayed departure flights",
       y = NULL,
       x = NULL) +
  geom_text(aes(label = number_flights),
            position = position_dodge(0.9),
            vjust = 0.5, hjust = -0.1) +
  theme_minimal() +
  xlim(0, 130000) +
  theme(
    panel.grid.major.y = element_blank(),
    legend.position = "bottom",
    legend.title = element_blank(),
    plot.title          = element_text(vjust = 3),
    plot.subtitle       = element_text(color = "grey30", vjust = 3)) +
  scale_fill_manual(values = c("firebrick", 
                               "grey60"))
```

## Percentage dep_delay variation per month
```{r}
library(lubridate)

# ----------------------------------------------------------------------------
# Total number of flights each NY airport had per month across all year 2017
# ----------------------------------------------------------------------------
flights_month_ny_airport <- flights_joined %>% 
  drop_na(dep_delay) %>% 
  group_by(month, name_airport) %>% 
  summarise(nr_flights = n())


# ----------------------------------------------------------------------------
# Total number of flights that departure delayed in each NY airport had per 
# month across all year 2017
# ----------------------------------------------------------------------------
flights_dep_delay_month_ny_airport <- flights_joined %>% 
  filter(dep_delay > 0) %>% 
  group_by(month, name_airport) %>% 
  summarise(nr_flights_dep_delay = n())

# ----------------------------------------------------------------------------
# Join
# ----------------------------------------------------------------------------
dep_delay_info <- 
  full_join(x = flights_month_ny_airport,
            y = flights_dep_delay_month_ny_airport) %>% 
  mutate(perc_dep_delay = round(x = nr_flights_dep_delay / nr_flights * 100, 
                                digits = 1))
  # summarise(across(.fns = ~sum(is.na(.x))))
  


# ----------------------------------------------------------------------------
# Plot - Percentage flights departure delay per month
# ----------------------------------------------------------------------------
dep_delay_info %>% 
  mutate(name_airport = factor(name_airport, levels = 
                                  c("Newark Liberty International Airport",
                                    "La Guardia Airport",
                                    "John F Kennedy International Airport"))) %>%
  ggplot(aes(x = month, y = perc_dep_delay, color = name_airport)) +
  geom_line(position = "dodge", aes(linetype = name_airport, size = name_airport)) +
  geom_point() +
  labs(title = "Percentage of delayed departure flights per month",
       subtitle = "New York Airports",
       y = NULL,
       x = NULL) +
  scale_y_continuous(labels = paste(c(seq(0,100, 10)), "%"),
                     breaks = seq(0, 100, 10),
                     limits = c(20, 50)) +
  scale_x_yearmonth(date_labels = "%Y \n %b", 
                    date_breaks = "1 month") +
  scale_color_manual(values = c("firebrick", 
                                "#D29F00", 
                                "steelblue")) +
  scale_size_manual(values = c(2, 0.8, 0.8)) +
  scale_linetype_manual(values = c("solid", "dashed", "dashed")) +
  theme_minimal() +
    theme(
        panel.grid.major.y  = element_line(size = 0.5, color = "grey70"),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        plot.title          = element_text(vjust = 3),
        plot.subtitle       = element_text(color = "grey30", vjust = 3),
        plot.caption  = element_text(size = 10, hjust = 0.5),
        legend.position = "bottom",
        legend.title = element_blank()
       )
```



# NEWARK AIRPORT
## Number fligths per month
```{r}
newark_flights <- flights_joined %>% 
  drop_na(dep_delay) %>% 
  group_by(month) %>% 
  summarise(flights_total = n())

newark_flights_ontime <- flights_joined %>% 
  drop_na(dep_delay) %>% 
  filter(dep_delay <= 0) %>% 
  group_by(month) %>% 
  summarise(flights_ontime = n())

newark_flights_delay <- flights_joined %>% 
  drop_na(dep_delay) %>% 
  filter(dep_delay > 0) %>% 
  group_by(month) %>% 
  summarise(flights_delay = n())


inner_join(x = newark_flights,
           y = newark_flights_ontime) %>% 
  inner_join(x = .,
             y = newark_flights_delay) %>%
  pivot_longer(cols = starts_with("flights_"),
               names_to = "flight",
               values_to = "count_flights") %>% 
  mutate(flight = factor(flight, levels = c("flights_total", "flights_ontime", "flights_delay"))) %>% 
  ggplot() +
  aes(x = month, y = count_flights, fill = flight) +
  geom_col(position = "dodge") +
  # geom_text(
  #   aes(label = count_flights), 
  #   position = position_dodge(0.9),
  #   angle = 90
  # ) +
  labs(title = "Newark Airport: number of flights per month",
       subtitle = "Departed on time VS Departed delayed",
       x = NULL,
       y = NULL) +
  scale_x_yearmonth(date_labels = "%b", 
                    date_breaks = "1 month") +
  scale_fill_manual(values = c("steelblue", 
                               "#D29F00",
                               "firebrick")) +
  theme_minimal()+
  theme(
    panel.grid.minor.x = element_blank(),
    panel.grid.major.x = element_blank(),
    plot.title = element_text(vjust = 3),
    plot.subtitle = element_text(color = "grey30", vjust = 3),
    legend.position = "bottom",
    legend.title = element_blank()
  )
```


## Number of flighs per Airline
```{r}
total_flights_airline <- flights_joined %>% 
  filter(origin == "EWR") %>% 
  group_by(name_airline) %>% 
  summarise(nr_flights = n()) 


total_flights_airline %>% 
  ggplot() +
  aes(x = nr_flights, y = reorder(name_airline, nr_flights), fill =  nr_flights == max(nr_flights)) +
  geom_col() + 
  geom_text(aes(label = nr_flights), 
            # position = position_stack(vjust = 0.5), 
            size = 4, 
            hjust = -0.1) +
  labs(title = "Total number of flights per Airline",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(
    panel.grid.major.y = element_blank(),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("grey60","steelblue")) +
  xlim(0, 60000)
```
```{r}
total_flights_airline <- flights_joined %>% 
  filter(origin == "EWR") %>% 
  group_by(name_airline) %>% 
  summarise(nr_departure_on_time = n()) 


delay_flights_airline <- flights_joined %>% 
  filter(origin == "EWR") %>% 
  filter(dep_delay > 0) %>% 
  group_by(name_airline) %>% 
  summarise(nr_departure_delay = n()) 

inner_join(total_flights_airline, 
           delay_flights_airline) %>% 
  mutate(perc = round(nr_departure_delay / nr_departure_on_time * 100, 
                      digits = 2)) %>% 
  pivot_longer(cols = c(2, 3),
               names_to = "departure",
               values_to = "value") %>% 


# total_flights_airline %>% 
  ggplot() +
  aes(x = value, y = reorder(name_airline, value), fill = departure) + 
      # fill =  value == max(value)) +
  geom_col(position = "dodge") + 
  geom_text(
    aes(label = value, x = value + 0.05),
    position = position_dodge(0.9),
    hjust = -.1
  ) +
  # geom_text(aes(label = value))+
            # position = position_stack(vjust = 0.5),
            # size = 4,
            # hjust = -0.1
            # ) +
  labs(title = "Total number of flights per Airline",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(
    panel.grid.major.y = element_blank(),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("grey60","firebrick")) +
  xlim(0, 60000)
```



## TOP 3 Airline with more delayed departure per month
```{r}
flights_joined %>% 
  filter(origin == "EWR") %>% 
  filter(dep_delay > 0) %>% 
  group_by(name_airline, month) %>% 
  summarise(nr_flights_delay = n()) %>%
  ungroup() %>%
  group_by(month) %>%
  slice_max(nr_flights_delay,
            n = 3, 
            with_ties = TRUE) %>% 
  mutate(name_airline= factor(name_airline, levels = c("United Air Lines Inc.",
                                                       "ExpressJet Airlines Inc.",
                                                       "JetBlue Airways"))) %>%
  ggplot() +
  aes(x = month, y = nr_flights_delay, fill = name_airline) %>% 
  geom_col(position = "dodge") +
  labs(
    title = "Top 3 airlines with more delayed departure per month",
    subtitle = "Number of flights",
    x = NULL,
    y = NULL
  ) +
  scale_x_yearmonth(date_labels = "%b", 
                    date_breaks = "1 month") +
  scale_fill_brewer(palette = 1, direction = -1) +
  # (values = c("firebrick", "#D29F00", "grey70")) +
  theme_minimal()+
  theme(
    panel.grid.minor.x = element_blank(),
    panel.grid.major.x = element_blank(),
    plot.title = element_text(vjust = 3),
    plot.subtitle = element_text(color = "grey30", vjust = 3),
    legend.position = "bottom",
    legend.title = element_blank()
  )
```

# Travel with the higher distance by company and how many times happened
```{r}
# Airline that has the flight with longer distance
# How many times this travel happen
# Percentage of this flight in total flights of these airline

flights_joined %>% 
  filter(origin == "EWR") %>% 
  group_by(name_airline, distance) %>% 
  summarise(nr_times = n()) %>%
  # ungroup() %>%
  # group_by(month) %>%
  slice_max(nr_times,
            n = 1, 
            with_ties = TRUE) %>% 
  arrange(desc(distance)) %>% 
  full_join(x = .,
            y = total_flights_airline) %>% 
  mutate(perc = round(nr_times / nr_flights * 100, digits = 1),
         text_plot = str_c(distance, " miles - ", 
                           nr_times, " times - ",
                           perc, "%", 
                           sep = "")) %>% 
  ggplot() +
  aes(x = distance, 
      y = reorder(name_airline, distance), 
      fill =  distance == max(distance)) +
  geom_col() +
  labs(title = "Travel with higher distance per airline company",
       subtitle = "Legend: distance of that flight - number of times that happened - which % represent of total flights of these airline",
       x = "distance (miles)",
       y = NULL) +
  geom_text(aes(label = text_plot),
            position = position_stack(vjust = 0.5),
            size = 3,
            hjust = -0.01
            ) +
  scale_fill_manual(values = c("grey60","firebrick")) +
  theme_minimal() +
  theme(
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    plot.title = element_text(vjust = 3),
    plot.subtitle = element_text(color = "grey30", vjust = 3),
    legend.position = "none",
    legend.title = element_blank()
  ) 
```









## Weather conditions
```{r}
# -----------------------------------------------------------------------------
# Mean value per weather condition by delayed departure flights and on time 
# departure flights
# -----------------------------------------------------------------------------

#Tidy data
setup <- flights_joined %>%
  rename(temperature = temp,
         precipitation = precip,
         visibility = visib,
         "wind direction" = wind_dir,
         "wind speed" = wind_speed,
         "wind gust" = wind_gust,
         ) %>% 
  pivot_longer(cols = c("temperature":"visibility"),
               names_to = "weather_condition",
               values_to = "value") %>% 
  select(weather_condition, value, month, dep_delay) %>% 
  group_by(weather_condition, month)


#mean value per weather condition for flights that departured on time
on_time <- setup %>% 
  filter(dep_delay <= 0) %>% 
  summarise(mean_on_time = mean(value, na.rm= TRUE))

#mean value per weather condition for flights that departure delayed
delay <- setup %>% 
  filter(dep_delay > 0) %>% 
  summarise(mean_delay = mean(value,  na.rm = TRUE))

#join data ontime and delayed and plot
inner_join(on_time, delay) %>% 
  pivot_longer(cols = starts_with("mean") , 
               names_to = "record",
               values_to = "value") %>% 
  ggplot() +
  aes(x = month, y = value, color = record) +
  geom_line(position = "dodge", size = 1) + 
  scale_x_continuous(breaks = seq(1, 12, 1)) +
  scale_x_yearmonth(date_labels = "%b", 
                    date_breaks = "2 month") +
  facet_wrap(~ weather_condition, scales = "free", ncol = 3) +
  scale_color_manual(values = c(
    "mean_on_time" = "seagreen",
    "mean_delay" = "firebrick")
  ) +
  labs(title = "Weather conditions (mean values) by flights departured delay and on time per month",
       subtitle = "Newark Airport",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(strip.background = element_rect(fill = "grey80", colour = "white"),
        strip.text       = element_text(face = "bold"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        plot.title = element_text(vjust = 3),
        plot.subtitle = element_text(color = "grey30", vjust = 3))
```

```{r}
# -----------------------------------------------------------------------------
# Which travel happen most (on time or with delay)?
#   - Number of fights per travel (origin to dest)
# -----------------------------------------------------------------------------
total_travel <- flights %>% 
  mutate(origin_dest = str_c(origin, dest, sep = " - ")) %>% 
  select(dep_delay, flight, air_time, distance, name_airports, origin_dest) %>% 
  drop_na(flight) %>% 
  filter(name_airports == "Newark Liberty International Airport") %>% 
  group_by(origin_dest) %>% 
  summarise(total_flight = n())
  

# -----------------------------------------------------------------------------
# Which travel with departure delay happen most?
#   - Number of fights per travel (origin to dest)
#   - Total minutes of departure delay per travel
# -----------------------------------------------------------------------------
travel_delay <- flights %>% 
  mutate(origin_dest = str_c(origin, dest, sep = " - ")) %>% 
  select(dep_delay, flight, air_time, distance, name_airports, origin_dest) %>% 
  drop_na(flight, dep_delay, distance, air_time) %>% 
  filter(name_airports == "Newark Liberty International Airport") %>% 
  filter(dep_delay > 0) %>% 
  group_by(origin_dest, name) %>% 
  summarise(nr_flight_delay = n(),
            # sum_dep_delay = sum(dep_delay),
            distance = mean(distance),
            mean_air_time = round(mean(air_time), digits = 0))

# -----------------------------------------------------------------------------
# join all
#   Here it is possible to see, by trip from origin to destination, which trip
#   ends up having the most delays in #  percentage terms.
# -----------------------------------------------------------------------------
travel_summary <- full_join(total_travel, travel_delay, by = "origin_dest") %>% 
  mutate(perc_dep_delay = round(nr_flight_delay / total_flight, digits = 3), 
         .after = nr_flight_delay) %>% 
  arrange(desc(total_flight))

travel_summary 
```


# Arrived delay per airline
```{r}
arrive_flights_airline <- flights_joined %>% 
  filter(origin == "EWR") %>% 
  filter(arr_delay > 0) %>% 
  mutate(name_airline = as.factor(name_airline)) %>% 
  group_by(name_airline) %>% 
  summarise(nr_arrive_delay = n()) %>% 
  arrange(desc(nr_arrive_delay))

arrive_flights_airline %>% 
  ggplot() +
  aes(
    x = nr_arrive_delay,
    y = reorder(name_airline, nr_arrive_delay),
    fill = name_airline
      ) + 
  geom_col() + 
  labs(title = "Number of flights with arrive delay per Airline",
       x = NULL,
       y = NULL) +
    geom_text(aes(label = nr_arrive_delay), 
            # position = position_stack(vjust = 0.5), 
            size = 4, 
            hjust = -0.1) +
  theme_minimal() +
  theme(
    panel.grid.major.y = element_blank(),
    legend.position = "none"
  ) + 
  scale_fill_manual(values = c("grey50", 
                               "grey50", 
                               "grey50", 
                               "#D29F00", #2
                               "#D29F00", #3
                               "grey50", 
                               "grey50", 
                               "grey50", 
                               "#D29F00", #1
                               "grey50")) +
xlim(0, 22000)

```

